README.rst
bugs.txt
common.py
run_gen.py
test_sets.txt
tmp_cleaner.sh

- runtime fails reduction
- creduce option can now take integral parameter passed to creduce in --n option
- more bugs in bugs.txt
- more known compfail messages for clang and gcc.
- adding info about active tasks in online one-line report
- adding clang after-crash scripts to list of files to cleanup in /tmp

Scripts improvements

---

src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/main.cpp
src/options.h
src/stmt.cpp
src/stmt.h
src/sym_table.cpp
src/sym_table.h
src/type.cpp
src/type.h
src/variable.cpp
test_sets.txt

Bunch of clean up changes:
- fix build on MacOS
- fix build with gcc
- fix gcc warnings
- convert a lot of "num" and "count" variables to un unsigned types
- a bit of C++14 features usage to improve the code readability
- change default settings for compiler options to be hardware neutral

Code clean up

---

run_gen.py
src/expr.cpp
src/master.cpp
src/type.cpp

- Add some more known gcc fails
- Avoid defaults in swithes
- Fix mistakenly commented break
- Avoid double curly braces in foo()

Minor fixes

---

README.md

The reasons - caching seems to break build badges for rst.

Converting README for rst to md.

---

.appveyor.yml
.travis.yml
CMakeLists.txt
README.md
src/CMakeLists.txt
src/expr.cpp
src/gen_policy.h
src/stmt.cpp
src/sym_table.cpp
src/sym_table.h
src/type.cpp

Moving build system to CMake to be able to easily compile for both Linux and Windows.
Also adding Appveyor CI - builds on Windows.
Still some clean up is required to build on Windows without warnings.

CMake and Appveyor CI support

---

bugs.rst

[32646](https://bugs.llvm.org/show_bug.cgi?id=32646) is invalid bug

Delete invalid bug

---

src/utils.cpp
src/utils.h

Currently, the random value generator is using a `long long` uniform distribution. Unfortunately, this is not correct for some types, like `unsigned long long`. The problem is, the `numeric_limits<unsigned long long>::max()` value cannot be represented as `long long`, and the following assertion will fire in STL: https://github.com/microsoft/STL/blob/68b344c9dcda6ddf1a8fca112cb9033f9e50e787/stl/inc/random#L1758
I added a `getRandUnsignedValue` function with `unsigned long long` uniform distribution to remedy the problem. Let me know if you had something else in mind.

Unsigned long long generator fix

---

src/context.cpp
src/context.h
src/data.cpp
src/data.h
src/expr.cpp
src/expr.h
src/stmt.cpp
src/stmt.h
src/type.cpp
src/type.h

The main idea of this commit is to separate loop bounds from arrays and iterators. From now on the loop itself determines valid range, and iterators and arrays are created with respect to this range. It allows us to simplify dependecies between different parts of the generator and builds foundation for pattern generation.

Change arrays and iterators generation

---

.appveyor.yml

Update Appveyor to install multilib corresponding to the latest compiler: `g++-9-multilib`.
This fixes Appveyor build on Ubuntu x86 (32 bit).

Fix Appveyor Ubuntu x86

---

src/context.cpp
src/context.h
src/enums.h
src/expr.cpp
src/gen_policy.h
src/main.cpp
src/options.cpp
src/options.h
src/stmt.cpp
src/utils.cpp
src/utils.h

The goal of this commit is to fix and improve experimental mutation mechanism that already exists in YARPGen.
Mutation mechanism is designed to produce tests that are almost the same, but differ in subtle details (e.g, they use different arithmetic expressions in some places). This feature is necessary for alive2 testing and allows us to expand YARPGen to new domains.
I've added various levels of mutation (scope, expressions) and isolated mutation decisions from the main logic.

Fix and improve mutation strategy

---

scripts/run_gen.py

We pass `target` arguments to `run_gen.py` as a string and parse it later. Right now makes it impossible to pass targets to docker container, so I added an option to separate them with comma

Fix parameters type

---

docker/Dockerfile

The current SDE version (sde-external-9.7.0-2022-05-09) does not work properly on some of the AMD chips to emulate sapphire rapids. The solution is to roll back to the previous version.

Roll back SDE version

---

docker/docker-entrypoint.sh
scripts/test_sets.txt

- `-fPIC -mcmodel=large` is needed to avoid crashes due to too large binary size. The downside is that previously these testes were crashing with clear compile time message, but now may consume too much resources in runtime.
- Change format of result folder name in docker. Now it's sortable and has time (allow disambiguation for multiple runs a day).

Adjust default options for C++ and change test results folder name

---

docker/docker-entrypoint.sh

The problem with previous string was usage of `%k`, which is **space** padded.

Fix date format for docker

---

scripts/check_isa.cpp

The `check_isa.cpp` file was ported from ISPC, it contains more platforms now and bug fixes, specifically https://github.com/ispc/ispc/issues/2504
The license was changed to Apache-2.0, as it's a compatible license and ISPC version is fully copyrighted by Intel.

Update check_isa.cpp with new arches and fixed bugs

---

LICENSE.txt
scripts/blame_opt.py
scripts/collect_other_stats.py
scripts/common.py
scripts/gen_test_makefile.py
scripts/run_gen.py
scripts/test_sets.txt
src/enums.h
src/expr.h
src/gen_policy.h
src/type.h

Fixes some small typos and such in the comments/strings/docs files

Typographical/Grammar Fixes

---

src/options.h

When I have tried to build yarpgen on ArchLinux
the build failed with
"/home/dima/work/yarpgen/src/options.h:122:5: error: ‘uint64_t’ does not name a type
122 |     uint64_t getSeed() { return seed; }
|     ^~~~~~~~
/home/dima/work/yarpgen/src/options.h:28:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’;..."

Add missing header.

---

src/stmt.cpp

The exact assertion text is "Vector iterators incompatible", but MSVC is right to assert here, in the (common) case where `taken_switch_id` isn't initialized.

Fix MSVC (correct) runtime assertion on uninitialized var

---

scripts/run_gen.py

Advancing towards running on windows

Make run_gen.py work on windows

---

.github/workflows/c-cpp.yml

Restrict token permissions used by CI pipeline

GA: set read-all permissions

---

src/gen_policy.cpp

With `-Werror` gcc-14.1.1 (with libstdc++-14) emits an error: `error: ignoring return value of _FIter std::remove_if(_FIter, _FIter, _Predicate) ... ...
declared with attribute nodiscard [-Werror=unused-result]`. Use cast to `void` to avoid it.

Fix compilation error with gcc-14.

---

scripts/common.py

Intel's SYCL implementation requires C++17 and this is baked by the SYCL 2020 specification, see:
- 3.9.1. Minimum version of C++ [1]
- 3.3. Normative references [2]
[1]: https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:progmodel.minimumcppversion
[2]: https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:normativerefs
Without this tweak, generated makefiles are not suitable for building SYCL programs with intel/llvm.

Set C++17 when generating SYCL programs

---

src/expr.cpp

SYCL 2020 specification does not define min/max overloads accepting `bool` data type, but yarpgen generates code that calls them. Of course, such code does not compile and to fix this, we do a promotion from `bool` to `char` (or `signed char`, to be precise).

Fix generation of min/max calls for SYCL
