src/type.cpp

Change UB detection in / and %

---

src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/main.cpp
src/stmt.cpp
src/stmt.h

The algorithm, which forms the probability of features, was changed.

Improve generated tests variety.

---

bugs.txt
common.py
run_gen.py

Adding creduce for compfails, adding regular runs of tmp_cleaner.sh during run_gen.py run and changing the default for log fail naming, which is now your test dir + .log

Scripts update

---

gen_test_makefile.py
run_gen.py
test_sets.txt

Now testing scripts are able to collect different statistics (number of applied optimizations / generated statements and expressions).

Statistics collector

---

src/expr.cpp
src/expr.h

Change min value emission for int types (issue #23)

---

src/program.cpp
src/program.h
src/stmt.cpp
src/stmt.h

- Move form_extern_sym_table from ScopeStmt to Master
- Fix extraction from symbol tables

Improvements

---

run_gen.py

-Explicitly mark tests "no_good_runs", when all of runs has failed.
-Explicitly ask to add ubsan run to creduce when failing
-Disable performance creduce hack, as it's not working for 2 file setup

Several script improvements

---

src/gen_policy.h
src/ir_node.h
src/sym_table.cpp
src/type.h
src/variable.h

Build errors

---

src/expr.cpp
src/expr.h
src/stmt.cpp
src/stmt.h

New approach to expression counter. The old one was bogus and didn't work properly.

New expression counter

---

src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/program.cpp
src/stmt.cpp
src/type.cpp

New kinds of constants:
1. Buffer for used constants + transformations on them (negation and bit not)
2. Magic numbers as constants (numbers, min/max values, bit blocks)
New utility functions and some code refactoring with them.

New approach to ConstExpr generation + code refactoring

---

blame_opt.py
bugs.txt
run_gen.py
tmp_cleaner.sh

- bug list update
- list of known fails update
- fix for not saving _only_ compile_time fails
- tmp cleaner improvement
- blaming fix

Minor updates

---

.clang-format
.gitignore
src/CMakeLists.txt
src/enums.h
src/ir_value.cpp
src/ir_value.h
src/main.cpp
src/type.cpp
src/type.h
src/type_test.cpp
src/utils.h

1. Finish implementation for Integral Types
Add folding set for Integral Types
2. Implement the majority of IRValue operators
3. Minor code style changes
4. Fix build

Integral types. IRValue oprerators implementations.

---

.appveyor.yml

Fix for Ubuntu build; adding VS2019

Appveyor update

---

.travis.yml
check_format.sh
src/data.cpp
src/data.h
src/enums.h
src/expr.cpp
src/options.cpp
src/options.h
src/program.cpp
src/stmt.cpp

* check_format.sh script to check formatting
* fix current formatting issues
* add check_format.sh to TravisCI
* add one more build to TravicCI with newly add Ubuntu 20.04/clang10

Check format

---

scripts/run_gen.py
src/CMakeLists.txt
src/data.cpp
src/data.h
src/emit_policy.cpp
src/emit_policy.h
src/enums.h
src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/options.cpp
src/options.h
src/program.cpp
src/statistics.cpp
src/statistics.h
src/stmt.cpp

Add aligned attribute and dead variables pruning

New version

---

check_isa.cpp
common.py
gen_test_makefile.py
run_gen.py
src/gen_policy.cpp
src/gen_policy.h
src/main.cpp
src/options.cpp
src/options.h
test_sets.txt

It is very preliminary and doesn't support a lot of features.

Add Windows support

---

README.md
scripts/run_gen.py
scripts/test_sets.txt
src/context.h
src/data.cpp
src/data.h
src/data_test.cpp
src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_test.cpp
src/ir_node.h
src/options.cpp
src/program.cpp
src/program.h
src/stmt.cpp
src/stmt.h
src/type.cpp
src/type.h

Add SYCL support to the generator. It is very preliminary work.

Add SYCL support to the generator

---

src/data.cpp
src/enums.h
src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/ir_value.cpp
src/ir_value.h
src/options.cpp
src/options.h
src/type.cpp
src/type.h
src/type_test.cpp
src/utils.h

Add features from old generator + fix some bugs

Old features

---

.appveyor.yml
src/CMakeLists.txt
src/context.cpp
src/context.h
src/data.cpp
src/data.h
src/data_test.cpp
src/enums.h
src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/ir_node.h
src/ir_value.cpp
src/options.cpp
src/options.h
src/stmt.cpp
src/stmt.h
src/type.cpp
src/type_test.cpp
src/utils.h

I've changed array and iterator generation logic to support stencils pattern.

Stencil patterns

---

src/enums.h
src/expr.cpp
src/gen_policy.cpp
src/gen_policy.h
src/options.cpp
src/options.h

Add Undefined Behavior in Dead Code that can be enabled with CLI.

Allow Undefined Behavior in Dead Code

---

docker/Dockerfile
scripts/build_binutils.sh
scripts/gen_test_makefile.py
scripts/test_sets.txt

Add new targets: Sapphire Rapids and Polly. The default binutils do not fully support spr, so we have to build the latest version by hand.

New targets

---

docker/Dockerfile

Binutils require "MPFR" library for the build

Fix binutils build

---

scripts/ispc-disp
scripts/test_sets.txt
src/context.cpp
src/context.h
src/data.cpp
src/data.h
src/data_test.cpp
src/enums.h
src/expr.cpp
src/expr.h
src/gen_policy.cpp
src/gen_policy.h
src/ir_value.cpp
src/ir_value.h
src/main.cpp
src/options.cpp
src/options.h
src/program.cpp
src/stmt.cpp
src/stmt.h
src/type.cpp
src/utils.h

This is a cumulative commit that brings all of the features that were living in separate branches together to the trunk.

Major feature update
